# Generated by Django 3.2.7 on 2021-11-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211106_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='title',
        ),
    ]
