# Generated by Django 3.2.7 on 2021-12-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
