# Generated by Django 3.2.7 on 2021-12-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
    ]
